Resources:
  # 患者情報テーブル
  PatientsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.PATIENTS_TABLE}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: NameIndex
          KeySchema:
            - AttributeName: name
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Project
          Value: CareARGlass

  # バイタルサインテーブル
  VitalsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.VITALS_TABLE}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      Tags:
        - Key: Project
          Value: CareARGlass

  # ケア記録テーブル
  CareRecordsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.CARE_RECORDS_TABLE}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
        - AttributeName: careType
          AttributeType: S
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: CareTypeIndex
          KeySchema:
            - AttributeName: patientId
              KeyType: HASH
            - AttributeName: careType
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Project
          Value: CareARGlass

  # デバイス管理テーブル
  DevicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.DEVICES_TABLE}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: deviceId
          AttributeType: S
        - AttributeName: assignedTo
          AttributeType: S
      KeySchema:
        - AttributeName: deviceId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: AssignedToIndex
          KeySchema:
            - AttributeName: assignedTo
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Project
          Value: CareARGlass

  # スタッフテーブル
  StaffTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.STAFF_TABLE}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: staffId
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: staffId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: NameIndex
          KeySchema:
            - AttributeName: name
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Project
          Value: CareARGlass

  # 家族ポータルアクセステーブル
  FamilyAccessTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.FAMILY_ACCESS_TABLE}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: accessId
          AttributeType: S
        - AttributeName: patientId
          AttributeType: S
      KeySchema:
        - AttributeName: accessId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: PatientIndex
          KeySchema:
            - AttributeName: patientId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Project
          Value: CareARGlass

Outputs:
  PatientsTableName:
    Value:
      Ref: PatientsTable
  VitalsTableName:
    Value:
      Ref: VitalsTable
  CareRecordsTableName:
    Value:
      Ref: CareRecordsTable
  DevicesTableName:
    Value:
      Ref: DevicesTable
  StaffTableName:
    Value:
      Ref: StaffTable
  FamilyAccessTableName:
    Value:
      Ref: FamilyAccessTable
